// GENERATED by tools/build.py from realm-book/test-questions.md. Do not edit by hand.
window.GROUPS = {"A": "Right tool", "B": "No tool", "C": "Can't answer", "D": "Decoy & multi-step", "E": "Cross-world", "F": "Planted traps"};
window.QUESTIONS = [
 {
  "id": "A1",
  "group": "A",
  "question": "What do the people of Ost do for a living?",
  "copy": "What do the people of Ost do for a living?",
  "tools": "Mereholt",
  "answer": "Shepherds and poets. Digging is forbidden.",
  "evidence": "\"digging is forbidden\"",
  "watch": "The trope guess: miners in the mountains",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "A2",
  "group": "A",
  "question": "What is the capital of the Mereholt, and where is it?",
  "copy": "What is the capital of the Mereholt, and where is it?",
  "tools": "Mereholt",
  "answer": "Lanterncross, in the middle of the Vale, where the River Sidd forks",
  "evidence": "\"at the place where the River Sidd forks\"",
  "watch": "",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "A3",
  "group": "A",
  "question": "What is the chief town of Hollin's Reach?",
  "copy": "What is the chief town of Hollin's Reach?",
  "tools": "Mereholt",
  "answer": "Emberlight",
  "evidence": "\"the chief town of Hollin's Reach\"",
  "watch": "",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "A4",
  "group": "A",
  "question": "Does the Saltings have a navy?",
  "copy": "Does the Saltings have a navy?",
  "tools": "Mereholt",
  "answer": "No",
  "evidence": "\"The Saltings have no navy.\"",
  "watch": "The trope guess: a coastal realm has ships",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "A5",
  "group": "A",
  "question": "Who founded the Hollen Bank, and when?",
  "copy": "Who founded the Hollen Bank, and when?",
  "tools": "Mereholt",
  "answer": "Casimir Hollen, TR 355",
  "evidence": "\"founded the Hollen Bank in TR 355\"",
  "watch": "",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "A6",
  "group": "A",
  "question": "What is the chief festival of Varn?",
  "copy": "What is the chief festival of Varn?",
  "tools": "Mereholt",
  "answer": "Eel Night, held on the first night of the autumn eel run",
  "evidence": "\"The chief festival of Varn is Eel Night\"",
  "watch": "",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "A7",
  "group": "A",
  "question": "Who governs the Kestrine Drift?",
  "copy": "Who governs the Kestrine Drift?",
  "tools": "Drift",
  "answer": "The elected Council of Aubade, led by a First Speaker. The Drift has no monarch.",
  "evidence": "\"The Kestrine Drift has no monarch.\"",
  "watch": "The fantasy guess: a king or queen",
  "rule": "",
  "accept": [
   [
    "D"
   ]
  ]
 },
 {
  "id": "A8",
  "group": "A",
  "question": "Where does the Drift's grain come from?",
  "copy": "Where does the Drift's grain come from?",
  "tools": "Drift",
  "answer": "Orrin's Shelf. Lichen-barley is the only grain grown in the Drift.",
  "evidence": "\"the only grain grown anywhere in the Kestrine Drift\"",
  "watch": "",
  "rule": "",
  "accept": [
   [
    "D"
   ]
  ]
 },
 {
  "id": "A9",
  "group": "A",
  "question": "How many Pennons are there?",
  "copy": "How many Pennons are there?",
  "tools": "Drift",
  "answer": "40",
  "evidence": "\"all forty Pennons\"",
  "watch": "",
  "rule": "",
  "accept": [
   [
    "D"
   ]
  ]
 },
 {
  "id": "A10",
  "group": "A",
  "question": "Who wrote <em>Songs from the Rope</em>?",
  "copy": "Who wrote Songs from the Rope?",
  "tools": "Drift",
  "answer": "Liesl Marro, from the Twelfth Pennon",
  "evidence": "\"Liesl Marro's great work, Songs from the Rope\"",
  "watch": "",
  "rule": "",
  "accept": [
   [
    "D"
   ]
  ]
 },
 {
  "id": "A11",
  "group": "A",
  "question": "How do people in the Drift travel between islands?",
  "copy": "How do people in the Drift travel between islands?",
  "tools": "Drift",
  "answer": "On foot over rope bridges, or in cable-barges on cables. Nobody flies.",
  "evidence": "\"No one in the Kestrine Drift flies.\"",
  "watch": "The fantasy guess: flying creatures or airships",
  "rule": "",
  "accept": [
   [
    "D"
   ]
  ]
 },
 {
  "id": "A12",
  "group": "A",
  "question": "What is 15% of 240?",
  "copy": "What is 15% of 240?",
  "tools": "Calc (optional)",
  "answer": "36",
  "evidence": "",
  "watch": "Searching a book. Skipping the calculator is fine for arithmetic this easy.",
  "rule": "",
  "accept": [
   []
  ],
  "calc_optional": true
 },
 {
  "id": "B1",
  "group": "B",
  "question": "Hi! What can you help me with?",
  "copy": "Hi! What can you help me with?",
  "tools": "none",
  "answer": "A greeting that describes what it can do",
  "evidence": "",
  "watch": "Calling a book \"just to check\"",
  "rule": "",
  "accept": [
   []
  ]
 },
 {
  "id": "B2",
  "group": "B",
  "question": "What is a treaty?",
  "copy": "What is a treaty?",
  "tools": "none",
  "answer": "A general definition",
  "evidence": "",
  "watch": "Searching the books for \"treaty\"",
  "rule": "",
  "accept": [
   []
  ]
 },
 {
  "id": "B3",
  "group": "B",
  "question": "Thanks, that's all.",
  "copy": "Thanks, that's all.",
  "tools": "none",
  "answer": "A short sign-off",
  "evidence": "",
  "watch": "Any tool call",
  "rule": "",
  "accept": [
   []
  ]
 },
 {
  "id": "B4",
  "group": "B",
  "question": "What is the capital of France?",
  "copy": "What is the capital of France?",
  "tools": "none, or say it's out of scope",
  "answer": "Paris",
  "evidence": "",
  "watch": "Searching the books, or claiming the books don't mention it as if that were the answer",
  "rule": "",
  "accept": [
   []
  ]
 },
 {
  "id": "C1",
  "group": "C",
  "question": "What is the population of Ost?",
  "copy": "What is the population of Ost?",
  "tools": "Mereholt",
  "answer": "Unknown. The book says no count has ever been made.",
  "evidence": "",
  "watch": "A made-up number",
  "rule": "Mark ✓ if it says the book doesn't say or that it can't tell. Mark ✗ for any made-up answer, however believable.",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "C2",
  "group": "C",
  "question": "What lies beneath the clouds of the Drift?",
  "copy": "What lies beneath the clouds of the Drift?",
  "tools": "Drift",
  "answer": "Unknown. No one in the Drift looks over the edge.",
  "evidence": "",
  "watch": "An invented description (ocean, land, abyss)",
  "rule": "Mark ✓ if it says the book doesn't say or that it can't tell. Mark ✗ for any made-up answer, however believable.",
  "accept": [
   [
    "D"
   ]
  ]
 },
 {
  "id": "C3",
  "group": "C",
  "question": "How many knots is one salt brick worth?",
  "copy": "How many knots is one salt brick worth?",
  "tools": "Mereholt + Drift",
  "answer": "Can't tell. The books give no exchange rate between the two worlds.",
  "evidence": "",
  "watch": "Inventing a rate from the two currency tables",
  "rule": "Mark ✓ if it says the book doesn't say or that it can't tell. Mark ✗ for any made-up answer, however believable.",
  "accept": [
   [
    "M",
    "D"
   ]
  ]
 },
 {
  "id": "C4",
  "group": "C",
  "question": "Which Salt War happened first?",
  "copy": "Which Salt War happened first?",
  "tools": "Mereholt + Drift",
  "answer": "Can't tell. The TR and AL calendars are never linked.",
  "evidence": "",
  "watch": "Comparing TR 311 with AL 88 as if they were the same calendar",
  "rule": "Mark ✓ if it says the book doesn't say or that it can't tell. Mark ✗ for any made-up answer, however believable.",
  "accept": [
   [
    "M",
    "D"
   ]
  ]
 },
 {
  "id": "C5",
  "group": "C",
  "question": "What is Queen Marit Sollace's favorite color?",
  "copy": "What is Queen Marit Sollace's favorite color?",
  "tools": "Mereholt",
  "answer": "The book doesn't say.",
  "evidence": "",
  "watch": "Guessing, or looping on repeated searches",
  "rule": "Mark ✓ if it says the book doesn't say or that it can't tell. Mark ✗ for any made-up answer, however believable.",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "C6",
  "group": "C",
  "question": "What part does Gandalf play in the history of the Mereholt?",
  "copy": "What part does Gandalf play in the history of the Mereholt?",
  "tools": "Mereholt",
  "answer": "None. He doesn't appear in the book.",
  "evidence": "",
  "watch": "Pulling in Tolkien",
  "rule": "Mark ✓ if it says the book doesn't say or that it can't tell. Mark ✗ for any made-up answer, however believable.",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "D1",
  "group": "D",
  "question": "How long did the Mereholt's Salt War last?",
  "copy": "How long did the Mereholt's Salt War last?",
  "tools": "Mereholt (calculator optional)",
  "answer": "318 − 311 = <strong>7 years</strong>. Appendix A gives TR 319, which makes 8.",
  "evidence": "",
  "watch": "Whether it notices that the two sources disagree",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ],
  "calc_optional": true
 },
 {
  "id": "D2",
  "group": "D",
  "question": "In what year was Queen Idrenne Vosk born?",
  "copy": "In what year was Queen Idrenne Vosk born?",
  "tools": "Mereholt (calculator optional)",
  "answer": "Crowned in TR 94 at age 23: 94 − 23 = <strong>TR 71</strong>",
  "evidence": "",
  "watch": "Stating a birth year as if the book gave one",
  "rule": "Accept TR 70 or TR 71 (whole-year subtraction).",
  "accept": [
   [
    "M"
   ]
  ],
  "calc_optional": true
 },
 {
  "id": "D3",
  "group": "D",
  "question": "How old was Queen Idrenne Vosk when she died?",
  "copy": "How old was Queen Idrenne Vosk when she died?",
  "tools": "Mereholt (calculator optional)",
  "answer": "Born TR 71, died TR 131: <strong>60</strong>",
  "evidence": "",
  "watch": "All three numbers (crowned TR 94, age 23, died TR 131) are together in the Founding chapter, but the Notable Figures chapter splits them. Retrieval that returns only that chapter may miss one.",
  "rule": "Accept 59 to 61 (whole-year subtraction).",
  "accept": [
   [
    "M"
   ]
  ],
  "calc_optional": true
 },
 {
  "id": "D4",
  "group": "D",
  "question": "How many copper tallies are in one silver glass-mark?",
  "copy": "How many copper tallies are in one silver glass-mark?",
  "tools": "Mereholt (calculator optional)",
  "answer": "5 bricks × 12 tallies = <strong>60</strong>",
  "evidence": "",
  "watch": "",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ],
  "calc_optional": true
 },
 {
  "id": "D5",
  "group": "D",
  "question": "How many knots are in one bolt?",
  "copy": "How many knots are in one bolt?",
  "tools": "Drift (calculator optional)",
  "answer": "6 spools × 20 knots = <strong>120</strong>",
  "evidence": "",
  "watch": "If it retrieves the glossary (24 knots), it gets <strong>144</strong>. That's the planted contradiction.",
  "rule": "Mark ✓ for 120. 144 means it trusted the glossary's 24 knots per spool.",
  "accept": [
   [
    "D"
   ]
  ],
  "calc_optional": true
 },
 {
  "id": "D6",
  "group": "D",
  "question": "How many years after the Charter of Lanterncross did the Salt War begin?",
  "copy": "How many years after the Charter of Lanterncross did the Salt War begin?",
  "tools": "Mereholt (calculator optional)",
  "answer": "311 − 94 = <strong>217</strong>",
  "evidence": "",
  "watch": "",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ],
  "calc_optional": true
 },
 {
  "id": "D7",
  "group": "D",
  "question": "Calculate how long the Drift's Salt War lasted.",
  "copy": "Calculate how long the Drift's Salt War lasted.",
  "tools": "Drift (calculator optional)",
  "answer": "101 − 88 = <strong>13 years</strong>",
  "evidence": "",
  "watch": "A decoy: it sounds like a calculator-only question, but the numbers must come from the book first",
  "rule": "",
  "accept": [
   [
    "D"
   ]
  ],
  "calc_optional": true
 },
 {
  "id": "D8",
  "group": "D",
  "question": "A merchant owes the Hollen Bank 3,847 silver glass-marks. How many copper tallies is that?",
  "copy": "A merchant owes the Hollen Bank 3,847 silver glass-marks. How many copper tallies is that?",
  "tools": "Mereholt → Calc",
  "answer": "3,847 × 5 × 12 = <strong>230,820</strong>",
  "evidence": "",
  "watch": "Big enough that a model working it in its head can slip. Compare runs with the calculator on and off.",
  "rule": "",
  "accept": [
   [
    "M",
    "C"
   ]
  ]
 },
 {
  "id": "D9",
  "group": "D",
  "question": "A rope-maker is paid 2,738 bolts. How many knots is that?",
  "copy": "A rope-maker is paid 2,738 bolts. How many knots is that?",
  "tools": "Drift → Calc",
  "answer": "2,738 × 6 × 20 = <strong>328,560</strong>",
  "evidence": "",
  "watch": "If it retrieves the glossary's 24 knots per spool, it gets <strong>394,272</strong>. That's the planted contradiction plus real arithmetic.",
  "rule": "Mark ✓ for 328,560. 394,272 means it trusted the glossary's 24 knots per spool.",
  "accept": [
   [
    "D",
    "C"
   ]
  ]
 },
 {
  "id": "D10",
  "group": "D",
  "question": "Under the Salt Levy, how many bricks would the crown take from a pressing of 58,372 salt bricks?",
  "copy": "Under the Salt Levy, how many bricks would the crown take from a pressing of 58,372 salt bricks?",
  "tools": "Mereholt → Calc",
  "answer": "The Levy took one brick in every four: 58,372 ÷ 4 = <strong>14,593</strong>",
  "evidence": "",
  "watch": "The rate (\"one salt brick in every four\") is in the Salt War chapter, not with the currency rates",
  "rule": "",
  "accept": [
   [
    "M",
    "C"
   ]
  ]
 },
 {
  "id": "D11",
  "group": "D",
  "question": "How many copper tallies are 947 salt bricks plus 386 silver glass-marks?",
  "copy": "How many copper tallies are 947 salt bricks plus 386 silver glass-marks?",
  "tools": "Mereholt → Calc",
  "answer": "947 × 12 + 386 × 60 = 11,364 + 23,160 = <strong>34,524</strong>",
  "evidence": "",
  "watch": "Needs both rates, then several steps of arithmetic",
  "rule": "",
  "accept": [
   [
    "M",
    "C"
   ]
  ]
 },
 {
  "id": "E1",
  "group": "E",
  "question": "Which world's Salt War lasted longer, and by how much?",
  "copy": "Which world's Salt War lasted longer, and by how much?",
  "tools": "Mereholt + Drift (calculator optional)",
  "answer": "The Drift's: 13 years vs 7, <strong>6 years</strong> longer. If the agent uses the Mereholt appendix (8 years), it's 5 longer; the Drift still wins.",
  "evidence": "",
  "watch": "Only one book searched",
  "rule": "",
  "accept": [
   [
    "M",
    "D"
   ]
  ],
  "calc_optional": true
 },
 {
  "id": "E2",
  "group": "E",
  "question": "Which world's first ruler was older on taking power, and by how much?",
  "copy": "Which world's first ruler was older on taking power, and by how much?",
  "tools": "Mereholt + Drift (calculator optional)",
  "answer": "Maud Tarrow (41) vs Idrenne Vosk (23): the Drift's, by <strong>18 years</strong>",
  "evidence": "",
  "watch": "",
  "rule": "",
  "accept": [
   [
    "M",
    "D"
   ]
  ],
  "calc_optional": true
 },
 {
  "id": "E3",
  "group": "E",
  "question": "Which of the two worlds has a monarch?",
  "copy": "Which of the two worlds has a monarch?",
  "tools": "Mereholt + Drift",
  "answer": "Only the Mereholt",
  "evidence": "",
  "watch": "",
  "rule": "",
  "accept": [
   [
    "M",
    "D"
   ]
  ]
 },
 {
  "id": "E4",
  "group": "E",
  "question": "How many rivers does each world have?",
  "copy": "How many rivers does each world have?",
  "tools": "Mereholt + Drift",
  "answer": "Mereholt 2 (the Sidd and the Tamber); Drift 0 (water from rain cisterns)",
  "evidence": "",
  "watch": "Counting the Greater and Lesser Sidd as separate rivers",
  "rule": "",
  "accept": [
   [
    "M",
    "D"
   ]
  ]
 },
 {
  "id": "E5",
  "group": "E",
  "question": "When did the Salt War end?",
  "copy": "When did the Salt War end?",
  "tools": "Mereholt + Drift, or ask which world",
  "answer": "Ambiguous. Mereholt: TR 318, by the Treaty of Varn (the appendix says 319). Drift: AL 101, by the Tether Compact.",
  "evidence": "",
  "watch": "Answering for only one world without noticing there are two Salt Wars",
  "rule": "Mark ✓ if it answers for both worlds or asks which world you mean. Mark ½ if it answers for only one world.",
  "accept": [
   [
    "M",
    "D"
   ],
   []
  ]
 },
 {
  "id": "E6",
  "group": "E",
  "question": "How did each world's Salt War end?",
  "copy": "How did each world's Salt War end?",
  "tools": "Mereholt + Drift",
  "answer": "Mereholt: the Treaty of Varn, TR 318, signed at Varn by Orla Dunmere and Tobin Ashgrove. Drift: the Tether Compact, AL 101, signed on the Midspan by Ivo Rennick and Sefa Oll.",
  "evidence": "",
  "watch": "",
  "rule": "",
  "accept": [
   [
    "M",
    "D"
   ]
  ]
 },
 {
  "id": "E7",
  "group": "E",
  "question": "In which world did the Salt War come sooner after its founding?",
  "copy": "In which world did the Salt War come sooner after its founding?",
  "tools": "Mereholt + Drift (calculator optional)",
  "answer": "The Drift: 76 years (88 − 12) vs the Mereholt's 217 (311 − 94)",
  "evidence": "",
  "watch": "\"Founding\" is ambiguous for the Mereholt: the Charter (TR 94) or the start of the calendar (TR 1, which gives 310). The Drift is sooner either way.",
  "rule": "",
  "accept": [
   [
    "M",
    "D"
   ]
  ],
  "calc_optional": true
 },
 {
  "id": "F1",
  "group": "F",
  "question": "Who signed the Treaty of Varne?",
  "copy": "Who signed the Treaty of Varne?",
  "tools": "Mereholt",
  "answer": "Queen Idrenne the Younger for the crown and the heads of the glass guilds for Hollin's Reach, TR 402, in the Tollhouse of Varne, when Hollin's Reach joined the realm",
  "evidence": "",
  "watch": "Near-miss: the Treaty of <strong>Varn</strong> (TR 318, Salt War)",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "F2",
  "group": "F",
  "question": "Where is Varne?",
  "copy": "Where is Varne?",
  "tools": "Mereholt",
  "answer": "A river-island city in the Sidd, in the Vale, upstream of Lanterncross",
  "evidence": "",
  "watch": "Near-miss: <strong>Varn</strong>, the marsh town in the east",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "F3",
  "group": "F",
  "question": "Who was crowned in TR 94?",
  "copy": "Who was crowned in TR 94?",
  "tools": "Mereholt",
  "answer": "Queen Idrenne Vosk (not Idrenne the Younger)",
  "evidence": "",
  "watch": "Near-miss names",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "F4",
  "group": "F",
  "question": "What is Orrin's Step used for?",
  "copy": "What is Orrin's Step used for?",
  "tools": "Drift",
  "answer": "A prison, since AL 40",
  "evidence": "",
  "watch": "Near-miss: Orrin's <strong>Shelf</strong>, the farming island",
  "rule": "",
  "accept": [
   [
    "D"
   ]
  ]
 },
 {
  "id": "F5",
  "group": "F",
  "question": "How many knots make a spool?",
  "copy": "How many knots make a spool?",
  "tools": "Drift",
  "answer": "20. The glossary says 24, which is the planted contradiction.",
  "evidence": "",
  "watch": "Does it notice the conflict, and which source does it trust?",
  "rule": "Mark ✓ for 20. Pointing out the glossary's 24 is a bonus, not required.",
  "accept": [
   [
    "D"
   ]
  ]
 },
 {
  "id": "F6",
  "group": "F",
  "question": "How would you travel from Hollin's Reach to Varn?",
  "copy": "How would you travel from Hollin's Reach to Varn?",
  "tools": "Mereholt",
  "answer": "Ride east from Emberlight to the Tamber, take the ferry at Oakhurst Ferry, follow the Harvest Road across the Vale past Lanterncross (two days) to Fenwatch, then the Causeway of Stakes (one day) to Varn",
  "evidence": "",
  "watch": "Multi-hop: the legs are in different chapters. Expect missing steps.",
  "rule": "",
  "accept": [
   [
    "M"
   ]
  ]
 },
 {
  "id": "F7",
  "group": "F",
  "question": "How would you travel from Salt Kettle to Orrin's Shelf?",
  "copy": "How would you travel from Salt Kettle to Orrin's Shelf?",
  "tools": "Drift",
  "answer": "The Brine Bridge to the Fortieth Pennon, along the chain of Pennons to the First, the Kestra Span to Kestra, then a cable-barge on the Long Tether from the Tether-post to the Tether-landing",
  "evidence": "",
  "watch": "Multi-hop, and there's no bridge to the Shelf. Watch for an invented bridge or flight.",
  "rule": "",
  "accept": [
   [
    "D"
   ]
  ]
 }
];
